### ISSUE TITLE
v0.7.1 release packed tar and zip not working

### ISSUE THREAD

**Issue by jctemp** [dashevo/tenderdash#351]
Want to use tenderdash v0.7.1 for a local network test. The zip and tar are incomplete to compile tenderdash.

## Expected Behavior
- execute `make build` or `make install-bls` with `make build-linux`
- compiling tenderdash from src

## Current Behavior
- failing at building tenderdash form src step
- error#1: `#include "chiabls/bls.hpp"` for `make build`
- error#2: `*** No rule to make target 'chiabls'.  Stop.` for `make install-bls`

## Possible Solution
- bls-signatures is a submodule and is therefore not properly packed

## Steps to Reproduce (for bugs)
1. download tar or zip file
2. unpack and change to directory
3. start building process

## Your Environment

* Version used: v0.7.1
* Operating System and version (desktop, server, or mobile): Ubunut Linux 64-bit
* Install tools: gcc 9.4.0, make 4.2.1, go1.18.1 linux/amd64

## Console output

![make build](https://user-images.githubusercontent.com/58829168/163668832-e28dad3a-ef57-4e95-8911-954921387b22.png)

**Comment by shotonoff** [comment]
Hi @jctemp, 
Thank you for informing us about this issue, I will take a look at adding a submodule into the release archive.
However, if you can't wait for then the easiest way is to use git clone of the `tenderdash`

**Comment by jctemp** [comment]
Yeah I did that already. Thank you 👍🏼

**Comment by shotonoff** [comment]
the PR #355 with a fix is ready for review

**Comment by shotonoff** [comment]
Hey @jctemp,
1. the fix merged
2. you also can get the `tenderdash` docker image [here](https://hub.docker.com/r/dashpay/tenderdash/)

**Comment by jctemp** [comment]
Are these changes available in the next release?

**Comment by jctemp** [comment]
Tested the packed release files for v0.8.0-dev.3 and did not work. Same for the v0.7.1 release.

Could it be that I understood the merge wrong?

**Comment by jctemp** [comment]
Sorry, v0.8.0-dev.3 is working. I retried the installation process in a new Ubuntu and noticed that it requires `cmake libgmp-dev`, which I forgot to install.

Thank you for the fix :)
